### ISSUE TITLE
vocab.t7 not found

### ISSUE THREAD

**Issue by Achilles-96** [kostyaev/sentence2vec#2]
dataset.lua:41:  local filename = "data/vocab.t7" 

vocab.t7 is missing. Can you tell me where can I get it or how can I generate it?

**Comment by kostyaev** [comment]
Here are the lines responsible for that: https://github.com/kostyaev/sentence2vec/blob/master/dataset.lua#L53-L65. This file is created during train phase from Cornell Movie-Dialogs Corpus.
I've also uploaded vocab.t7 and updated the readme section.

**Comment by Achilles-96** [comment]
Thanks a lot :dancer:
